### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by theseusyang** [bitloops/bitloops-workflow#24]
when launch  `yarn start`, error bellowing:

bitloops/bitloops-engine/dist/util/stringManipulator.js:5
    return str.replace(new RegExp(find, 'g'), replace);
               ^

TypeError: Cannot read property 'replace' of undefined

**Comment by theseusyang** [comment]
add `str !=null` into codes

**Comment by danias** [comment]
Hi @theseusyang 

*yarn start* should only be used by a startup script in docker or Kubernetes. 

If you want to start the Bitloops Engine on development mode try yarn *start:dev* and make sure you have .env.dev in place with the appropriate values as can be found in *env-blueprint*.
